#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
 
source ${OPENSHIFT_HOMEDIR}python-2.7/virtenv/bin/activate

export PYTHON_EGG_CACHE=${OPENSHIFT_HOME_DIR}python-2.7/virtenv/lib/python-2.7/site-packages

echo "Executing 'python ${OPENSHIFT_REPO_DIR}manage.py syncdb --noinput'"
python "$OPENSHIFT_REPO_DIR"manage.py syncdb --noinput

cat "$OPENSHIFT_REPO_DIR"/static/bower_components/jquery/dist/jquery.min.js "$OPENSHIFT_REPO_DIR"/static/js/main.js "$OPENSHIFT_REPO_DIR"/static/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js > "$OPENSHIFT_REPO_DIR"/static/js/all.js
 
echo "Executing 'python ${OPENSHIFT_REPO_DIR}manage.py collectstatic --noinput -v0'"
python "$OPENSHIFT_REPO_DIR"manage.py collectstatic --noinput -v0

python "$OPENSHIFT_REPO_DIR"websocket_server.py --noinput -v0
