#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

echo "Stop websocket_server.py"
killall websocket_server.py > /dev/null 2>&1
exit 0
