# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='fr',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='it',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
