# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_auto_20170414_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='es',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='fr',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='it',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='ru',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='uk',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
