# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0009_auto_20170815_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='palate_color_1',
            new_name='palette_color_1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='palate_color_2',
            new_name='palette_color_2',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='palate_color_3',
            new_name='palette_color_3',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='palate_color_4',
            new_name='palette_color_4',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='palate_color_5',
            new_name='palette_color_5',
        ),
    ]
