# Generated by Django 2.0 on 2017-12-19 17:54

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tool', '0019_auto_20171217_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('visibility', models.CharField(choices=[('me', 'Visible just for me'), ('users', 'Visible only for resisted user'), ('link', 'Visible for all who has the link'), ('all', 'Visible for all')], default='all', max_length=6)),
                ('text', django.contrib.postgres.fields.jsonb.JSONField()),
                ('slug', models.CharField(max_length=10, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_fragments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
