# Generated by Django 2.0 on 2017-12-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0020_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='text',
            field=models.TextField(),
        ),
    ]
