# Generated by Django 2.0 on 2017-12-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0021_auto_20171222_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='visibility',
        ),
    ]
