# Generated by Django 2.0 on 2017-12-24 12:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tool', '0022_remove_code_visibility'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='code',
            unique_together={('title', 'user')},
        ),
    ]
