# Generated by Django 2.0 on 2017-12-24 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tool', '0023_auto_20171224_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='word',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('word', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('title', 'user')},
        ),
    ]
