# Generated by Django 2.0 on 2017-12-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0024_auto_20171224_1805'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
    ]
