# Generated by Django 2.0.2 on 2018-02-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0028_auto_20180227_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='resolution',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ("won't fix", "Won't Fix"), ('duplicate', 'Duplicate'), ('incomplete', 'Incomplete'), ('Cannot Reproduce', 'Cannot Reproduce'), ('obsolete', 'Obsolete'), ('works as designed', 'Works as Designed'), ('done', 'Done'), ("won't Do", "Won't Do")], max_length=16, null=True),
        ),
    ]
