# Generated by Django 2.0.2 on 2018-03-01 21:12

from django.contrib.auth import get_user_model
from django.db import migrations

from tool.models import Label

User = get_user_model()


class Migration(migrations.Migration):
    def add_labels(apps, schema_editor):
        labels = ('Apache', 'Bash', 'CoffeeScript', 'C++', 'C#', 'CSS', 'Diff',
                  'HTTP', 'Ini', 'Java', 'JavaScript', 'JSON', 'Makefile',
                  'Markdown', 'Nginx', 'Objective-C', 'Perl', 'PHP', 'Python',
                  'Ruby', 'Shell Session', 'SQL', 'HTML, XML')
        for title in labels:
            label = Label(title=title, category='programing')
            label.save()

    dependencies = [
        ('tool', '0030_auto_20180301_2112'),
    ]

    operations = [
        migrations.RunPython(add_labels),
    ]