# Generated by Django 2.0.3 on 2018-03-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0033_auto_20180305_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='weight',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='code',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text='Used programming languages will be automatically saved as labels.', to='tool.Label'),
        ),
        migrations.AlterField(
            model_name='code',
            name='text',
            field=models.TextField(help_text='Double click on code block to copy or edit.'),
        ),
    ]
