# Generated by Django 2.0.3 on 2018-03-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0034_auto_20180310_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=128),
        ),
    ]
