# Generated by Django 2.1 on 2018-08-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0039_auto_20180810_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='tool.Label'),
        ),
        migrations.AlterField(
            model_name='label',
            name='category',
            field=models.CharField(choices=[('programing', 'Programing'), ('links', 'Links')], default='programing', max_length=16),
        ),
    ]
