# Generated by Django 2.1 on 2018-08-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0040_auto_20180810_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/media/avatars/no-avatar.png', upload_to='avatars/'),
        ),
    ]
