# Generated by Django 3.0.2 on 2020-01-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0045_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='resolution',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ("won't fix", "Won't Fix"), ('duplicate', 'Duplicate'), ('incomplete', 'Incomplete'), ('Cannot Reproduce', 'Cannot Reproduce'), ('obsolete', 'Obsolete'), ('works as designed', 'Works as Designed'), ('done', 'Done'), ("won't Do", "Won't Do")], max_length=20, null=True),
        ),
    ]
