# Generated by Django 3.1.7 on 2021-03-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0048_auto_20210307_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='category',
            field=models.CharField(choices=[('fruit-veg', 'Fruit & vegetables'), ('meat-fish', 'Meat & fish'), ('food-cupboard', 'Food cupboard'), ('household', 'Household'), ('bakery', 'Bakery'), ('health-beauty', 'Toiletries & health'), ('dairy-eggs-and-chilled', 'Dairy, eggs & chilled'), ('frozen', 'Frozen')], default='fruit-veg', max_length=32),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
