# Generated by Django 3.2.3 on 2021-05-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0049_auto_20210308_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(default='Groceries', max_length=32, verbose_name='list name'),
        ),
    ]
